name: sam2lca
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - click=7.1.2
  - ete3=3.1.2
  - nbsphinx=0.8.1
  - ordered-set=4.0.2
  - pandas=1.2.1
  - pandoc=2.11.4
  - pip=21.0.1
  - pysam=0.16.0.1
  - python
  - python-rocksdb=0.7.0
  - recommonmark=0.7.1
  - rocksdb=6.13.3
  - setuptools=49.6.0
  - sphinx=3.4.3
  - sphinx-click=2.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinx_rtd_theme=0.5.1
  - sphinxcontrib-serializinghtml=1.1.4
  - tqdm=4.56.0
  - xopen=1.1